service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-tracing # トレース有効用のプラグイン
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  tracing: true # X-Rayでのトレースを有効にする

functions:
  apiGet:
    handler: api.get
    events:
      - http:
          method: get
          path: api
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
